lost_socks/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lost_socks.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls',namespace='main')),
)

main/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'freelancer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'main.views.main',name='main'),
    url(r'^check_activation$', 'main.views.check_activation',name='check_activation'),
    url(r'^report$', 'main.views.report',name='report'),
    url(r'^activate$', 'main.views.activate',name='activate'),
    url(r'^message$', 'main.views.message',name='message'),
    url(r'^signup$', 'main.views.signup',name='signup'),
    url(r'^signout$', 'main.views.signout',name='signout'),
    url(r'^signin$', 'main.views.signin',name='signin'),
    url(r'^profile$', 'main.views.profile',name='profile'),


    # url(r'^category/(?P<category_id>.+)$', 'main.views.category',name='category'),
    # url(r'^brand/(?P<brand_id>.+)$', 'main.views.brand',name='brand'),
    # url(r'^model/(?P<model_id>.+)$', 'main.views.model',name='model'),
    # url(r'^instance/(?P<instance_id>.+)$', 'main.views.instance',name='instance'),
    # url(r'^add_instance/phones$', 'main.views.add_instance_phones',name='add_instance_phones'),
    # url(r'^add_instance/notebooks$', 'main.views.add_instance_notebooks',name='add_instance_notebooks'),    
    #url(r'^signin$', 'main.views.signin',name='signin'),
    #url(r'^signup$', 'main.views.signup',name='signup'),
    #url(r'^signout$', 'main.views.signout',name='signout'),
)

main/models.py
from django.db import models
from datetime import datetime 
from django.contrib.auth.models import User

class Cardstick(models.Model):
	""" Card info """

	card_id = models.CharField(max_length = 7, unique=True)
	activated = models.BooleanField(default = False)
	telephone = models.CharField(max_length = 20,default = "",null=True, blank=True)
	email = models.CharField(max_length = 50,default = "",null=True, blank=True)
	name = models.CharField(max_length = 100,default = "",null=True, blank=True)

	def __unicode__(self):
		return self.card_id

	class Meta:
		verbose_name = "Карта"
		verbose_name_plural = "Карты"

class Mail(models.Model):
	name = models.CharField('имя отправителя',max_length=100,default = "",null=True, blank=True)
	email = models.CharField(max_length=100,default = "",null=True, blank=True)
	title = models.CharField('тема',max_length=100,default = "",null=True, blank=True)
	body = models.CharField('сообщение',max_length=1000,default = "",null=True, blank=True)
	date = models.DateTimeField('дата отправления', default=datetime.now)
	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name = "сообщение"
		verbose_name_plural = "сообщения"
		

main/views.py
#importings
from django.shortcuts import render_to_response, redirect, get_object_or_404, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Cardstick, Mail
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
import re
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse , reverse_lazy
#impoer of models 

def main(request):
	#initialize variables
	args={}
	args.update(csrf(request))
	return render(request, 'main/main.html',args)

def check_activation(request):
	#initialize variables
	args={}
	args.update(csrf(request))
	if request.POST:
		card_id = request.POST['idcode']
		card = Cardstick.objects.filter(card_id = card_id)
		if card.count() > 0:
			card = card[0]
			if card.activated == True:
				message = "Данная карта уже использована, попробуйте еще раз ..."
				args['message'] = message
				return render_to_response('main/check_activation.html',args)
			else:
				args['card_id'] = card.card_id
				message = "Пожалуйста завершите активацию карты."
				args['message'] = message
				return render_to_response('main/activate.html', args)
		else:
			message = "Данный код не действителен, попробуйте еще раз ..."
			args['message'] = message
			return render_to_response('main/check_activation.html',args)
	else:
		return redirect(reverse('main:main'))
	

def report(request):
	#initialize variables
	args={}
	args.update(csrf(request))
	if request.POST:
		card_id = request.POST['card_id']
		card = Cardstick.objects.filter(card_id = card_id)
		if card.count() > 0:
			card = card[0]
			if card.activated == True:
				message = "Пожалуйста свяжитесь с владельцем"
				info = Cardstick.objects.get(card_id = card_id)
				args['info'] = info
			else:
				message = "Данная карта еще не активирована"
		else:
			message = "Данный код не действителен, попробуйте еще раз ..."
		args['message'] = message
		return render_to_response('main/report.html',args)

	else:
		return redirect(reverse('main:main'))

def activate(request):
	#initialize variables
	args={}
	args.update(csrf(request))
	if request.POST:
		name = request.POST['name']
		email = request.POST['email']
		telephone = request.POST['telephone']
		card_id = request.POST['card_id']
		card = Cardstick.objects.get(card_id = card_id)
		card.name = name
		card.email = email
		card.telephone = telephone
		card.activated = True
		
		card.save()
		args["message"] = "Вы успешно активировали идентификатор. "

		return render_to_response('main/thanks_page.html', args)
	else:
		message = "Пожалуйста завершите активацию карты."
		args['message'] = message

	return render_to_response('main/activate.html',args)

def message(request):
	#initialize variables
	args={}
	args.update(csrf(request))
	if request.POST:
		name = request.POST['name']
		email = request.POST['email']
		subject = request.POST['subject']
		message = request.POST['message']
		mail = Mail.objects.create(name=name,email=email,title=subject,body=message)
		mail.save()
	return redirect(reverse('main:main'))

def signin(request):
	# redirect to main page authorized users
	if request.user.is_authenticated():
		return redirect(reverse("main:main"))
	# initialize variables
	args={}
	args.update(csrf(request))

	if request.POST:
		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(username=username, password=password)

		if user is not None:
			if user.is_active:
				login(request, user)
				return redirect(reverse('main:main'))
		else:
			args['error_message'] = "Имя пользователя и пароль не совпадают, попробуйте еще раз. "
			return render(request, 'main/signin.html', args)
	else:
		return render(request, 'main/signin.html', args)

@login_required(login_url=reverse_lazy('main:main'))
def signout(request):

	logout(request)
	return redirect(request.META.get('HTTP_REFERER'))

def signup(request):
	# redirect not authenticated users to main page
	if request.user.is_authenticated():
		return redirect(reverse("main:main"))
	# initialize variables
	args={}
	args.update(csrf(request))
	validation = True
	# Query objects from model
	all_users = User.objects.all()

	if request.POST:
		first_name = request.POST.get('first_name', '')
		email = request.POST.get('e_mail', '')
		password = request.POST.get('password', '')
		username = email

		# email validation
		users_using_email = all_users.filter(email=email)

		if not re.match(r"^[A-Za-z0-9\.\+_-]+@[A-Za-z0-9\._-]+\.[a-zA-Z]*$", email):
			validation = False
			args['email_error'] = 'Неправильно введен email'
		else:
		    if users_using_email.count() > 0:
			    validation = False
			    args['email_error'] = 'Этот email уже зарегистрирован'
			    args['email'] = email
			    args['first_name'] = first_name
		if validation == False:
			return render(request, 'main/signup.html', args)
		else:
			user = User.objects.create_user(username=username, email=email, password=password)
			user.first_name = first_name
			user.save()
			user = authenticate(username=username, password=password)
			login(request, user)
			return redirect(reverse('main:main'))
	else:
		return render(request, 'main/signup.html', args)

@login_required(login_url=reverse_lazy('main:signin'))
def profile(request):
	# initialize variables
	args={}
	args.update(csrf(request))

	return render(request, 'main/profile.html', args)

main/templates/main/profile.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Lost.Kg</title>
	<!-- core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css'%}'%}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/animate.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.css'%}" rel="stylesheet">
    <link href="{% static 'css/owl.transitions.css'%}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css'%}" rel="stylesheet">
    <link href="{% static 'css/main.css'%}" rel="stylesheet">
    <link href="{% static 'css/responsive.css'%}" rel="stylesheet">



   
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">


</head><!--/head-->
<body id="home" class="homepage">


    <header id="top-header" class="navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- /responsive nav button -->
                    
                    <!-- logo -->
                    <div class="navbar-brand">
                        <a href="{% url 'main:main' %}" >
                            <h4 style="color:white; font-size:24px;"><span style="color:red"></span>Lost.Kg</h4>
                        </a>
                    </div>
                    <!-- /logo -->
                </div>

                <!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="navigation">
                    <div class="main-menu-fake">
                        <ul id="nav" class="nav navbar-nav">
                            <li class="scroll"><a href="{% url 'main:main'%}#portfolio" data-section="#portfolio">Как это работает</a></li>
                            <li class="scroll"><a href="#contact-area" data-section="#contact-area">Обратная связь</a></li>   
                            <li class="scroll"><a href="{% url 'main:profile'%}">{{user.username}}</a></li>
                            <li><a href="{% url 'main:signout' %}">Выйти</a> </li>
                        </ul>
                    </div>
                </nav>
                <!-- /main nav -->
            </div>
        </header>

    <section id="main-slider">
    <div class="container">
        <div class="buttons-wrapper" style="position: absolute; top:15%; left:35%; z-index:1000; background-color:RGBA(0,0,0,0.41); border:5px solid RGBA(0,0,0,0.41);">
            <div class="buttons-wrapper-inner">
                <div class="activate-id-code text-center" >
                    <h2 style="color:orange">Профиль</h2>
                    <br>
                    <h3 style="color: white">Email : {{user.username}}</h3>
                    <hr>
                    <h3 style="color: white">Ф.И.О : {{user.first_name}}</h3>
                </div>
            </div>
        </div>
    </div>

        <div class="owl-carousel">
            <div class="item" style="background-image: url({% static 'images/slider/bg11.jpg'%});">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-2"></div>
                            <div class="col-md-8">
                               
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->
            <div class="item" style="background-image: url({% static 'images/slider/bg2.jpg'%});">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                        <div class="col-md-2"></div>
                            <div class="col-md-8">
                        </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->
            <div class="item" style="background-image: url({% static 'images/slider/bg13.jpg'%});">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                        <div class="col-md-2"></div>
                            <div class="col-md-8">
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->
            
        </div><!--/.owl-carousel-->
    </section><!--/#main-slider-->
    <section id="contact-area">
        <div class="container">
            <div class="row">
                <div class="section-header">
                    <h2 class="section-title text-center wow fadeInDown animated" style="visibility: visible;">Обратная Связь</h2>
                    <p class="text-center wow fadeInDown animated" style="visibility: visible;">Отправить сообщение .</p>
                </div>
                <form name="contact-form" method="post" action="{% url 'main:message'%}">
                {% csrf_token %}
                    <div class="col-lg-6 animated animate-from-left" style="opacity: 1; left: 0px;">

                        <div class="form-group">
                                <label for="name">Ф.И.О</label>
                                <input id="name" type="text" name="name" class="form-control" placeholder="Имя Фамилия" required>
                            </div>
                        <div class="form-group">
                                <label for="email">Email адрес</label>
                                <input type="email" id="email" name="email" class="form-control" placeholder="Email" required>
                            </div>
                        <div class="form-group">
                            <label for="subject">Тема</label>
                            <input type="text" id="subject" name="subject" class="form-control" placeholder="Тема" required>
                        </div>
                    </div>
                    <div class="col-lg-6 animated animate-from-right" style="opacity: 1; right: 0px;">
                        <div class="form-group">
                            <label for="message">Сообщение</label>
                            <textarea name="message" id="message" class="form-control" rows="8" placeholder="Сообщение" required></textarea>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="text-center">
                          <button type="submit" class="btn btn-primary btn-lg btn-send-msg">Отправить</button>
                    </div>

                </form>

            </div>
        </div>
    </section><!--/#bottom-->

    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <p class="text-center">
                        &copy; 2016 Lost.kg </a>
                    </p>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mousescroll.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/jquery.isotope.min.js' %}"></script>
    <script src="{% static 'js/jquery.inview.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript">
        function autoFill(){
            document.getElementById('card_id').value = document.getElementById('id-code-input1').value;
        };
    </script>
</body>
</html>

main/templates/main/signin.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Lost.Kg</title>
	<!-- core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css'%}'%}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/animate.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.css'%}" rel="stylesheet">
    <link href="{% static 'css/owl.transitions.css'%}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css'%}" rel="stylesheet">
    <link href="{% static 'css/main.css'%}" rel="stylesheet">
    <link href="{% static 'css/responsive.css'%}" rel="stylesheet">



   
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">


</head><!--/head-->
<body id="home" class="homepage">


    <header id="top-header" class="navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- /responsive nav button -->
                    
                    <!-- logo -->
                    <div class="navbar-brand">
                        <a href="{% url 'main:main' %}" >
                            <h4 style="color:white; font-size:24px;"><span style="color:red"></span>Lost.Kg</h4>
                        </a>
                    </div>
                    <!-- /logo -->
                </div>

                <!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="navigation">
                    <div class="main-menu-fake">
                        <ul id="nav" class="nav navbar-nav">
                            <li class="scroll"><a href="{% url 'main:main'%}#portfolio" data-section="#portfolio">Как это работает</a></li>
                            <li class="scroll"><a href="#contact-area" data-section="#contact-area">Обратная связь</a></li>   
                            <li class="scroll"><a href="{% url 'main:signup' %}">Зарегистрироваться</a></li>
                        </ul>
                    </div>
                </nav>
                <!-- /main nav -->
            </div>
        </header>

    <section id="main-slider">
    <div class="container">
        <div class="buttons-wrapper" style="position: absolute; top:45%; left:35%; z-index:1000; background-color:RGBA(0,0,0,0.41); border:5px solid RGBA(0,0,0,0.41);">
            {% if error_message %}
                <div class="alert alert-danger" role="alert">{{error_message}}<br></div>
            {% endif %}
            <div class="buttons-wrapper-inner">
                <div class="activate-id-code">
                    <form method="post" class="text-center" action="{% url 'main:signin'%}" id="activateCode">
                    {% csrf_token %}
                        <h2 class="text-center" style="color:orange">Войти</h2>
                        <div class="form-group ">
                          <label for="input-10">
                            <span style="color: white">Email</span>
                          </label>
                          <input style="margin-right: 123px; height: 33.5px;" required name = "username" class="form-control" placeholder="bachu@gmail.com" type="text" id="input-10" />
                        </div>
                        <div class="form-group">
                          <label for="input-11">
                            <span style="color: white">Пароль</span>
                          </label>
                          <input required name = "password" class="form-control" type="password" id="input-11" />
                        </div>
                        <br>
                        <div class="input-append text-center">
                            <input type="submit" style="margin-right: -4px;padding: 5.7px 15px;" class="btn btn-info btn-activate-now" value="&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspВойти&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp" id="activatenow"/>
                        </div>
                         <br>
                    </form>
                    <!--
                    <form method="post" action="{% url 'main:report'%}" style="display:inline">
                    {% csrf_token %}
                        <input type="hidden" value="" name="card_id" id="card_id" required>
                        <input type="submit" name="btnreport" id="btnreport" style="padding: 5.7px 15px;"class="btn btn-primary btn-found" value="Сообщить о Находке"/>
                    </form>
                    -->

                </div>
            </div>
        </div>
    </div>

        <div class="owl-carousel">
            <div class="item" style="background-image: url({% static 'images/slider/bg11.jpg'%});">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-2"></div>
                            <div class="col-md-8">
                                <div class="carousel-content text-center">
                                    <br><br><br><br>
                                    <div style="background-color:RGBA(255,255,255,0.9);"><h1>Добро пожаловать в проект <span style="color:red">LOST.kg!</span></h1>
                                        <p style="font-size:20px; color:#272727">Защита от потери ценных вещей</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->
            <div class="item" style="background-image: url({% static 'images/slider/bg2.jpg'%});">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                        <div class="col-md-2"></div>
                            <div class="col-md-8">
                                <div class="carousel-content text-center">
                                <br><br><br><br>
                                    <div style="background-color:RGBA(255,255,255,0.9);"><h1>Добро пожаловать в проект <span style="color:red">LOST.kg!</span></h1>
                                        <p style="font-size:20px; color:#272727">Защита от потери ценных вещей</p>
                                    </div>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->
            <div class="item" style="background-image: url({% static 'images/slider/bg13.jpg'%});">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                        <div class="col-md-2"></div>
                            <div class="col-md-8">
                                <div class="carousel-content text-center">
                               <br><br><br><br>
                                    <div style="background-color:RGBA(255,255,255,0.9);"><h1>Добро пожаловать в наш проект <span style="color:red">LOST.kg!</span></h1>
                                        <p style="font-size:20px; color:#272727">Защита от потери ценных вещей</p>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->
            
        </div><!--/.owl-carousel-->
    </section><!--/#main-slider-->
    <section id="contact-area">
        <div class="container">
            <div class="row">
                <div class="section-header">
                    <h2 class="section-title text-center wow fadeInDown animated" style="visibility: visible;">Обратная Связь</h2>
                    <p class="text-center wow fadeInDown animated" style="visibility: visible;">Отправить сообщение .</p>
                </div>
                <form name="contact-form" method="post" action="{% url 'main:message'%}">
                {% csrf_token %}
                    <div class="col-lg-6 animated animate-from-left" style="opacity: 1; left: 0px;">

                        <div class="form-group">
                                <label for="name">Ф.И.О</label>
                                <input id="name" type="text" name="name" class="form-control" placeholder="Имя Фамилия" required>
                            </div>
                        <div class="form-group">
                                <label for="email">Email адрес</label>
                                <input type="email" id="email" name="email" class="form-control" placeholder="Email" required>
                            </div>
                        <div class="form-group">
                            <label for="subject">Тема</label>
                            <input type="text" id="subject" name="subject" class="form-control" placeholder="Тема" required>
                        </div>

                    </div>
                    <div class="col-lg-6 animated animate-from-right" style="opacity: 1; right: 0px;">
                        <div class="form-group">
                            <label for="message">Сообщение</label>
                            <textarea name="message" id="message" class="form-control" rows="8" placeholder="Сообщение" required></textarea>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="text-center">

                          <button type="submit" class="btn btn-primary btn-lg btn-send-msg">Отправить</button>

                    </div>

                </form>

            </div>
        </div>
    </section><!--/#bottom-->

    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <p class="text-center">
                        &copy; 2016 Lost.kg </a>
                    </p>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mousescroll.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/jquery.isotope.min.js' %}"></script>
    <script src="{% static 'js/jquery.inview.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript">
        function autoFill(){
            document.getElementById('card_id').value = document.getElementById('id-code-input1').value;
        };
    </script>
</body>
</html>